baseURL = 'https://www.sotai.co/'
languageCode = 'en-us'
title = 'Sotai'
theme = 'ananke'

[menus]
  [[menus.main]]
    name = 'Products'
    url = '/products/'
    weight = 20
  [[menus.main]]
    name = 'Docs'
    url = '/docs/'
    weight = 20
